controller_manager:
  ros__parameters:
<<<<<<< HEAD
    update_rate: 100  # Hz
=======
    update_rate: 2  # Hz
>>>>>>> e87ddc4 (Corrections.)

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

fts_broadcaster:
  ros__parameters:
<<<<<<< HEAD
    sensor_name: tcp_fts_sensor
=======
    interface_names.force.x: tcp_fts_sensor/force.x
    interface_names.torque.z: tcp_fts_sensor/torque.z
>>>>>>> e87ddc4 (Corrections.)
    frame_id: tool_link
