name: Foxy RHEL Binary Build
on:
  pull_request:
    branches:
      - foxy
  push:
    branches:
      - foxy
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  foxy_rhel_binary:
    name: Foxy RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: foxy
    container: jaronl/ros:foxy-alma
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/ros2_control_demos
      - run: |
          rosdep update
          rosdep install -iy --from-path src/ros2_control_demos
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
